# Generated by Django 4.0.1 on 2022-02-05 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='prfssn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.profession'),
        ),
    ]
